# Generated by Django 4.0.4 on 2022-05-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_libraries', '0002_alter_userpost_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('posts', models.ManyToManyField(to='content_libraries.userpost')),
            ],
        ),
    ]
