# Generated by Django 4.0.4 on 2022-05-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contentGallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalbum',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_albums', to='accounts.client'),
        ),
    ]
